/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package impacta;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NumberRangesTests {
    @Test void singleOnEnds() {
        String in = "   1,3,6,7,8,12,13,14,15,21,22,23,24,31";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("1, 3, 6-8, 12-15, 21-24, 31", range.summarizeCollection(range.collect(in)));
    }

    @Test void rangeOnEnds() {
        String in = "3,4,5,8,11,13,14,15,16,17,19,23,24,25";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("3-5, 8, 11, 13-17, 19, 23-25", range.summarizeCollection(range.collect(in)));
    }

    @Test void oneRange() {
        String in = "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("1-21", range.summarizeCollection(range.collect(in)));
    }

    @Test void noRange() {
        String in = "1,3,5,7,9,11,13,15,17,19";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("1, 3, 5, 7, 9, 11, 13, 15, 17, 19", range.summarizeCollection(range.collect(in)));
    }

    @Test void whiteSpaces() {
        String in = "   1, 3,6, 7,8,9,12 ,14,15,16, 18,19 , 21";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("1, 3, 6-9, 12, 14-16, 18-19, 21", range.summarizeCollection(range.collect(in)));
    }

    @Test void outOfOrder() {
        String in = "1,6,3,9,8,12,14,21,16,18,19,7,15";
        NumberRanges range = new NumberRanges();
        System.out.println(range.summarizeCollection(range.collect(in)));
        assertEquals("1, 3, 6-9, 12, 14-16, 18-19, 21", range.summarizeCollection(range.collect(in)));
    }
}
